const projectsData = [
  //CO Blog Posts
  {
    id: 1,
    name: "Unveiling Bridal Style: Discover the Perfect Engagement Ring for Every Bride",
    tags: ["SEO"],
    image: "unveiling-bridal-style.jpg",
    completionDate: "2023-07-18",
  },
  {
    id: 2,
    name: "SCS-007 Certification: For a Sustainable Diamond Industry",
    tags: ["SEO"],
    image: "scs-007-certification.jpg",
    completionDate: "2023-07-12",
  },
  {
    id: 3,
    name: "The Most Expensive Engagement Ring Worn by a Celebrity",
    tags: ["SEO"],
    image: "most-expensive-ring.jpg",
    completionDate: "2023-06-20",
  },
  {
    id: 4,
    name: "What Diamond Shapes Look Biggest on an Engagement Ring",
    tags: ["SEO"],
    image: "biggest-diamond-shapes.jpg",
    completionDate: "2023-06-14",
  },
  {
    id: 5,
    name: "Meeting the Parents",
    tags: ["SEO"],
    image: "meeting-the-parents.jpg",
    completionDate: "2023-06-07",
  },
  {
    id: 6,
    name: "The Lauren Sanchez Engagement Ring",
    tags: ["SEO"],
    image: "lauren-sanchez.jpg",
    completionDate: "2023-06-03",
  },
  {
    id: 7,
    name: "Shopping Guide for Engagement Rings - Houston, TX",
    tags: ["SEO"],
    image: "shopping-guide-houston.jpg",
    completionDate: "2023-05-19",
  },
  {
    id: 8,
    name: "Shopping Guide for Engagement Rings - Dallas, TX",
    tags: ["SEO"],
    image: "shopping-guide-dallas.jpg",
    completionDate: "2023-05-18",
  },
  {
    id: 9,
    name: "Recycled Gold Jewelry",
    tags: ["SEO"],
    image: "recycled-gold.jpg",
    completionDate: "2023-05-11",
  },
  {
    id: 10,
    name: "Celebrity Men's Wedding Bands",
    tags: ["SEO"],
    image: "celebrity-wedding-bands.jpg",
    completionDate: "2023-05-10",
  },
  {
    id: 11,
    name: "Custom Engagement Rings at Clean Origin",
    tags: ["SEO"],
    image: "custom-rings.jpg",
    completionDate: "2023-05-04",
  },
  {
    id: 12,
    name: "How to Measure Ring Size: A Comprehensive Guide",
    tags: ["DESIGN", "SEO"],
    image: "ring-size.jpg",
    completionDate: "2023-05-03",
  },
  {
    id: 13,
    name: "Keep Your Conscience Clean With Ethical Diamonds",
    tags: ["SEO"],
    image: "ethical-diamonds.jpg",
    completionDate: "2023-04-20",
  },
  {
    id: 14,
    name: "Find the Perfect Fit With a Stud Earring Size Chart",
    tags: ["SEO"],
    image: "earring-size-chart.jpg",
    completionDate: "2023-04-14",
  },
  {
    id: 15,
    name: "Western Wedding Rings: The Perfect Blend of Tradition and Style",
    tags: ["SEO"],
    image: "western-rings.jpg",
    completionDate: "2023-04-12",
  },
  {
    id: 16,
    name: "Types of Diamonds",
    tags: ["SEO"],
    image: "diamond-types.jpg",
    completionDate: "2023-02-08",
  },
  {
    id: 17,
    name: "Engagement Rings Under $2,000",
    tags: ["SEO"],
    image: "2000-rings.jpg",
    completionDate: "2023-02-06",
  },
  {
    id: 18,
    name: "Engagement Rings for Women: 9 Engagement Ring Shopping Tips",
    tags: ["SEO"],
    image: "9-tips.jpg",
    completionDate: "2023/01/12",
  },

  //TP Articles
  {
    id: 19,
    name: "A Weapon Geralt Wields Sharper Than Steel or Silver",
    tags: ["SEO"],
    image: "geralt-empathy.jpg",
    completionDate: "2022/10/19",
  },
  {
    id: 20,
    name: "The Bard's Largest Contribution Isn't His Music",
    tags: ["SEO"],
    image: "dandelion.jpg",
    completionDate: "2022/12/10",
  },
  {
    id: 21,
    name: "The Witcher: Blood Origin Review - A Story Meant for Everyone That Satisfies No One",
    tags: ["SEO"],
    image: "blood-origin.jpg",
    completionDate: "2023/01/08",
  },
  {
    id: 22,
    name: "The Dangers of Success: The Last of Us, Episode 4 Review",
    tags: ["SEO"],
    image: "tlou-4.jpg",
    completionDate: "2023/02/10",
  },
  {
    id: 23,
    name: "Who Are We but Our Memories? A Dive Into Ellie's Past: The Last of Us Episode 7 Review",
    tags: ["SEO"],
    image: "tlou-7.jpg",
    completionDate: "2023/03/02",
  },
  {
    id: 24,
    name: "The Last of Us Season 1 Overall Review - The Best Live-Action Video Game Adaptation",
    tags: ["SEO"],
    image: "tlou-s1.jpg",
    completionDate: "2023/03/19",
  },
  {
    id: 25,
    name: "The Witcher's Story Is Not Geralt's Alone",
    tags: ["SEO"],
    image: "ciri.jpg",
    completionDate: "2023/03/24",
  },

  // Marketing
  {
    id: 26,
    name: "Sales Emails and Case Studies Content Creation",
    tags: ["SEO"],
    image: "case-studies.jpg",
    completionDate: "2023/03/31",
  },

  // Websites
  {
    id: 27,
    name: "The Path Website Redesign",
    tags: ["DESIGN", "DEVELOPMENT", "SEO"],
    image: "tp-website.jpg",
    completionDate: "2023/04/06",
  },
  {
    id: 28,
    name: "HubSpot Landing Page Code Updates",
    tags: ["DESIGN", "DEVELOPMENT"],
    image: "module-updates.jpg",
    completionDate: "2023/06/20",
  },
  {
    id: 29,
    name: "Website Module Responsiveness",
    tags: ["DEVELOPMENT"],
    image: "module-responsiveness.jpg",
    completionDate: "2023/07/28",
  },
];

export default projectsData;
